# Generated by Django 5.1.4 on 2024-12-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_division_remove_category_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
