# Generated by Django 5.1.4 on 2024-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
