# Generated by Django 5.1.4 on 2024-12-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dealer_approved',
            field=models.BooleanField(default=False),
        ),
    ]
